version: '3.1'

services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    container_name: 'gitlab'
    hostname: 'xgro' # hostname
    # environment:
      # GITLAB_OMNIBUS_CONFIG: |
      #   external_url 'http://gitlab.example.com' 
      # 외부 ip 혹은 접근할 ip
      # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '8080:80' # http 접근포트 
      - '8443:443' # https 접근포트 
      - '8022:22' # ssh 접근포트
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'